name: CI
on:
  push:
    branches:
      - stainless
  pull_request:
    branches:
      - stainless

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    

    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5

      - name: Run lints
        run: ./scripts/lint
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5

      - name: Bootstrap
        run: ./scripts/bootstrap

      - name: Run tests
        run: ./scripts/test

